### ISSUE TITLE
bad citekeys in bibtex file

### ISSUE THREAD

**Issue by thibaud** [willsALMANJ/lyz#11]
Hi,

Lyz is really great, it's really a super idea. So well, that I can use it with a strange behavior. When I add a reference with the lyz button in lyx, I got an error with for example (Benghozi, ??) : the year is replaced by ??. In the bib file, I got  the key "0_XWFBWGD7" in the first line, so lyx can't compile well the bibtex file. For example: 
﻿@article{russell1999nosignificant, 0_XWFBWGD7

I'm used to correct manually the file for every new cite. I thought that when I uncheck the  "Create cite key ?" settings, it was possible to correct this behavior, but it's not the case.
But today I thought that it was possible to improve my lyz experience. So what I have not understand trying lyz plugin ?

Best,
Thibaud.

**Comment by willsALMANJ** [comment]
Hi Thibaud,

sorry, but I can't quite follow all of what you say. The key in the first line should not be a problem for LyX. It is okay to delete them though. They are only useful if you want to import from the .bib file into Zotero.

What do you have for your citekey in your LyZ settings? You shouldn't uncheck the "Create cite key?" box unless you are using a custom BibTeX translator that generates its own cite key. What is the whole entry that appears in the .bib file? If you use Zotero's standard BibTeX translator to export a .bib file, what does the same entry look like?

Also, what version of LyX and LaTeX are you using? I haven't tried using LyZ with the most recent versions recently.

**Comment by willsALMANJ** [comment]
By the way, I tried LyZ with the most recent version of LyX and Zotero and it still works for me. I'm closing this issue for now. It can be reopened if you want to investigate it further.
