### ISSUE TITLE
Zotero standalone cannot install lyz

### ISSUE THREAD

**Issue by ganong123** [willsALMANJ/lyz#15]
Hi,

I followed the instructions posted [here](https://blogs.eui.eu/zotero/how-to-use-zotero-with-lyx.html) to install Lyz with Zotero 4.0.15.29 running Mac OS X Sierra. Error:

```
The add-on "LyZ" could not be installed. It may be incompatible with this version of Zotero Standalone.
```

Is there a newer .xpi file I should be using? Or any other tips to make this work?

Thanks, Peter

**Comment by willsALMANJ** [comment]
Yes, those instructions are very old. Try downloading the latest version here: https://addons.mozilla.org/en-US/firefox/addon/lyz/

**Comment by ganong123** [comment]
I tried that and it didn't work. I think I need an xpi file.

**Comment by willsALMANJ** [comment]
That is where you download the xpi file. If you are using Firefox, right-click the but on that says "Add to Firefox" and choose "Save link as". If you are using a different browser, click the small link that says "download any way" under the "Only with Firefox" button.

**Comment by ganong123** [comment]
Thanks. That worked. I'm now getting a second set of errors (both in Firefox-based Zotero and in desktop-based) when I select a citation and choose "Cite in LyX". (A bit of context: I've used Zotero/Lyx/LyZ integration successfully in the past. Just got a new computer and trying to get everything set up there.)

I get three errors in succession
```
SERVER ERROR:
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://lyz/content/lyz.js :: Zotero.Lyz.lyxPipeInit :: line 137"  data: no]

Could not contact server at: \\.\pipe\lyxpipe

Could not retrieve document name.
```

My Lyx server pipe is set to "~/.lyxpipe" per the setup instructions for LyZ.

Also, I'm happy to move this question over to a new issue if you would prefer.

Thanks for your help!

**Comment by willsALMANJ** [comment]
You need to update the LyX pipe location in LyZ's settings as well. The default location is `\\.\pipe\lyxpipe` which is the default for Windows. On other systems you will see those errors because the Windows path formatting is invalid for OS X/Unix.

**Comment by ganong123** [comment]
That worked -- thanks! Step 2 of the current installation instructions reads "Open LyX and set LyXServer path (in LyX go to menu, Tools > Preferences... > Paths and set LyXServer pipe to): Windows users can use the default path setting in LyZ, i.e. \\.\pipe\lyxpipe. Linux and Mac users can use e.g. ~/.lyxpipe and change the LyZ settings accordingly." I'd suggest adding a bit more detail of how exactly to update LyZ settings for the newbs who get confused like me. Thanks again!

**Comment by willsALMANJ** [comment]
Glad it worked. Yes, it could be clearer. LyZ could also detect the operating system and use a different default path for OS X than for Windows. Firefox and Zotero are undergoing a lot of change right now, so I'm not too motivated to make updates to LyZ until the future of Zotero plugins is more clear.
