### ISSUE TITLE
Vancouver style requires 'journal'

### ISSUE THREAD

**Issue by MavropaliasG** [willsALMANJ/lyz#16]
Hello,

Thank for this great plugin. However when I try to cite in vancouver style I get this error

`journal' is a missing field, not a string, for entry avloniti2014theacute0_8 while executing---line 1865 of 
file `vancouver.bst`

and of course in the output the reference has no journal name or pages for that matter.

http://imgur.com/a/FC54c

Please let me know what I should do.

Thanks

**Comment by willsALMANJ** [comment]
That error is from LyX? I tried importing that citation into Zotero, citing it in LyX with LyZ, and then generating a bibliography with the vancouver style and it generated a reasonable looking output without an error (I don't know Vancouver well enough to say if it was right). Does the citation have Publication and Journal Abbrev entries in Zotero? You might try importing it into Zotero again if it does not have all the  fields needed by the Vancouver style. I also wonder why the citekey ends in "0_8" -- are there a lot of duplicate entries? For me the citekey was just "avloniti2014theacute".

**Comment by MavropaliasG** [comment]
Dear @willsALMANJ thank you very much for the reply and the wonderful plugin you made.

I have provided some pictures so I can show you my problem in more detail

http://imgur.com/a/l3X4J

I have used another reference to show you that its not a problem with the particular reference.

Please let me know what I should do.

Thanks

**Comment by willsALMANJ** [comment]
I looks like the problem is that you have "Use journal abbreviations" selected in LyZ's settings, but the reference you are citing has no "Journal Abbrev" entry in Zotero. You could either uncheck the abbreviation option in LyZ's settings or enter the journal abbreviation in Zotero manually.

The error you are getting is that there is no "journal" entry in the BibTeX file for that citation which vancouver.bst requires. You could look at the .bib file to check. It looks like it is stored at /home/machine/Downloads/12.

**Comment by MavropaliasG** [comment]
I unchecked the "Use journal abbreviations" and the problem remained. However if you check in the previous picture I sent you, in LyZ I used BibLatex instead of Bibtex.

Now I chose Bibtex and it displays this error

![screenshot from 2017-02-24 21-24-45](https://cloud.githubusercontent.com/assets/13523909/23305045/d704a5fa-fad7-11e6-8428-e48e7045e8b9.png)

what is wrong ?

**Comment by MavropaliasG** [comment]
@willsALMANJ  I made a new document and a new bib library and everything seems to be working just fine now. The problem was in BibLatex instead of Bibtex. I appologize for the inconvenience.

**Comment by willsALMANJ** [comment]
It looks maybe vancouver.bst doesn't know how to handle the /url entry in the BibTeX file. Try deleting the URL entry from the Zotero item and then do your test again.

**Comment by MavropaliasG** [comment]
@willsALMANJ that fixed it, thank you very much

**Comment by willsALMANJ** [comment]
I'm glad it's working for you now. I think that is the easiest workaround. It is a little annoying. I have had that issue in the past. I think either modified Zotero's BibTeX translator so it didn't output the URL or modified the .bst file so it ignored the URL, but those are more technical solutions (I don't remember how to do either -- I'd have to try it out).
