### ISSUE TITLE
LyZ no longer works with Zotero 5.0 (and Firefox plugin has been broken)

### ISSUE THREAD

**Issue by AkenSec** [willsALMANJ/lyz#18]
Firefox has dropped support for the old style of browser plugins, in favour of WebExtensions (see here: https://www.zotero.org/blog/a-unified-zotero-experience/).

Unfortunately, this has broken LyZ, as it's no longer possible to use the old Zotero Firefox plugin which LyZ was designed to work with. I'm not sure if Zotero 5.0 supports add-ins to the extent that it would be possible to port LyZ to work with the new stand-alone application.

**Comment by willsALMANJ** [comment]
I ported LyZ to Zotero 5.0 a while ago. It is possible to run add-ons in Zotero 5.0. This can be done through the Add-ons Manager window. On Linux, this is accessible from the Tools menu (the "Add-ons" item). The menu might be different on Windows or MacOS. Click the gear in the upper right and "Install add-on from file..." and then choose LyZ. You have to have downloaded the xpi file before doing that. The xpi can be downloaded from https://addons.mozilla.org/en-US/firefox/addon/lyz/ (if using Firefox, right-click the "Add to Firefox" button and choose "Save as...").

The LyZ install documentation needs to be updated.

Zotero 5.0 is basically Firefox with the old Zotero add-on preinstalled, so it's not that much of a departure. They are buffering themselves from the upcoming changes that make it impossible to use Zotero in Firefox while they work on moving to a new framework (Electron).

Please try it out and let me know if you have any problems. I haven't used LyZ in a while. I tested just now and it seemed to work for me. Ideally there would be unit tests but with Zotero in a state of flux my motivation for working on LyZ is pretty low until we see how the move to Electron goes and what the add-on system will be like there.

**Comment by AkenSec** [comment]
Ah thanks mate, I didn't realise that Zotero 5.0 could install the standard Firefox add-ons. You're an absolute lifesaver - I thought I'd be doing the rest of my thesis using copy-paste from Zotero into a .bib file.

It's working fine for me (macOS Sierra with LyX 2.2.3).

**Comment by cossio** [comment]
@willsALMANJ Perhaps these instructions can be added to the README.md?

**Comment by willsALMANJ** [comment]
@cossio Yes, I was leaving #25 open until I could do that -- it should not take much work to update it, but I haven't had free time. Also, I want to make the GitHub page the main download location when I have time, rather than addons.mozilla.org (which doesn't give a download option on browsers other than Firefox).
