### ISSUE TITLE
Lyz not working with Juris-M

### ISSUE THREAD

**Issue by maras** [willsALMANJ/lyz#20]
Hi.
Thank you for maintaining Lyz. Is there any plans for Lyz to work with Juris-M? Juris-M is more feature-rich version of Zotero with multilingual support and more. It would be nice to work with Lyx and Juris-M with the help of Lyz.

**Comment by willsALMANJ** [comment]
Sure, as long as it doesn't become too onerous to support both versions. I think I added the pieces necessary for LyZ to work in Juris-M. You can try it out:

[lyz.zip](https://github.com/willsALMANJ/lyz/files/1351064/lyz.zip)

**Comment by maras** [comment]
It is working as expected. Thank you!
