### ISSUE TITLE
Same labels for multiple items (webpage citation)

### ISSUE THREAD

**Issue by Beatzekatze** [willsALMANJ/lyz#21]
I am facing the problem that Zotero gives same labels to different websites when they are cited **simultaneously**. Here are some simple steps to reproduce the issue:
 
- add following two websites to a collection in Zotero:
 http://www.who.int/csr/don/2003_03_12/en/
 http://www.who.int/ihr/about/en/
- Change creator last name to something, e.g. WHO
- (Is it intended that when no creator name is entered the label is empty?)
- select **both** at the same time an cite in Lyx creating a new bib-File (BibFile1)
- in a new Lyx file (hence creating a new bib-File, BibFile2) cite the websites **one after** another

What I get is

BibFile 1:

> 1_KNUQHDXE 1_GY3EXHZ7
> 
> 
> @misc{who,
> 	title = {{WHO} {\textbar} {About} {IHR}},
> 	url = {http://www.who.int/ihr/about/en/},
> 	abstract = {Through IHR, countries have agreed to build their capacities to detect, assess and report public health events. WHO plays the coordinating role in IHR and, together with its partners, helps countries to build capacities.},
> 	urldate = {2017-10-10},
> 	journal = {WHO},
> 	author = {WHO},
> 	file = {Snapshot:/Users/obaranov/Zotero/storage/7DNQHKUZ/en.html:text/html}
> }
> @misc{who,
> 	title = {{WHO} {\textbar} {Acute} respiratory syndrome in {Hong} {Kong} {Special} {Administrative} {Region} of {China}/ {Viet} {Nam}},
> 	url = {http://www.who.int/csr/don/2003_03_12/en/},
> 	urldate = {2017-10-10},
> 	journal = {WHO},
> 	author = {WHO},
> 	file = {Snapshot:/Users/obaranov/Zotero/storage/4GAXX7YI/en.html:text/html}
> }

Bib-File 2:

>  1_GY3EXHZ7 1_KNUQHDXE
> 
> 
> @misc{who,
> 	title = {{WHO} {\textbar} {Acute} respiratory syndrome in {Hong} {Kong} {Special} {Administrative} {Region} of {China}/ {Viet} {Nam}},
> 	url = {http://www.who.int/csr/don/2003_03_12/en/},
> 	urldate = {2017-10-10},
> 	journal = {WHO},
> 	author = {WHO},
> 	file = {Snapshot:/Users/obaranov/Zotero/storage/4GAXX7YI/en.html:text/html}
> }
> 
> @misc{who2,
> 	title = {{WHO} {\textbar} {About} {IHR}},
> 	url = {http://www.who.int/ihr/about/en/},
> 	abstract = {Through IHR, countries have agreed to build their capacities to detect, assess and report public health events. WHO plays the coordinating role in IHR and, together with its partners, helps countries to build capacities.},
> 	urldate = {2017-10-10},
> 	journal = {WHO},
> 	author = {WHO},
> 	file = {Snapshot:/Users/obaranov/Zotero/storage/7DNQHKUZ/en.html:text/html}
> }

Is it a known bug? Or am I misunderstanding something?

**Comment by willsALMANJ** [comment]
It appears to be an unknown bug. The `checkAndCite` function loops over the selected items and adds them to the .bib file, generating cite keys for each, and then loops over the keys and adds them to the database. The cite key generation function modifies the key if a different item in the database already has that key, but that doesn't help if the key has just been generated and hasn't been added to the database yet.

It looks like the easiest solution is to check against the other cite keys generated in the loop when the new cite keys are generated. The cite key generation also needs to do a better check of the existing cite keys. Right now, it checks for keys that start with the same text as the potential new key and adds the number of matches plus one onto the end of the key. So if you had who and who2 and then who got deleted and then re-added, it would be added as a second who2.

**Comment by willsALMANJ** [comment]
I think I fixed the problem. Here is a zip you can install. I am not sure how well this new version works with an existing database that has duplicate citekeys in it already (though I don't think the old version of LyZ was handling that well any way).
[lyz.zip](https://github.com/willsALMANJ/lyz/files/1378984/lyz.zip)

**Comment by Beatzekatze** [comment]
Works, thank you! (Not with the DB with duplicates, but in new DBs the bug is gone).  And sorry for the late reply
