### ISSUE TITLE
Compatibility with Firefox Quantum

### ISSUE THREAD

**Issue by oussbenk** [willsALMANJ/lyz#22]
I enjoy using LyZ extension when writing LyX documents.
Is there any update soon to **support the new Firefox Quantum version**?
Thanks.

**Comment by willsALMANJ** [comment]
Sorry, that is not possible. LyZ is a plugin to Zotero so it has to follow whatever Zotero does. Zotero stopped supporting its Firefox version a little while ago and now only supports its standalone version. LyZ still works with the Zotero standalone client. You can read about Zotero's decision here: https://www.zotero.org/blog/a-unified-zotero-experience/ The short version is that Firefox Quantum does not provide enough functionality to support all of Zotero's features.

**Comment by oussbenk** [comment]
That's okay. It worked perfectly on Zotero standalone version. Indeed, I have never used LyZ with the standalone version before. It seems however to do things as well as the embedded Firefox plugin.
Many thanks for your great job and keep going on making it always working.
