### ISSUE TITLE
Where to download *.xpi for Zotero standalone?

### ISSUE THREAD

**Issue by Michael-Logies** [willsALMANJ/lyz#25]
Hello, can you provide a download link for installing Lyz within Zotero standalone? I have left Firefox, because the Zotero-add-on for Chrome has more features. (I downloaded Lyz with Firefox ESR but I`m stuck, because I don`t find "lyz.xpi" there). Thanks, Michael

**Comment by willsALMANJ** [comment]
You should be able to download the xpi using the "download any way" button on this page: https://addons.mozilla.org/en-US/firefox/addon/lyz/versions/

I am attaching the latest version from that page. I had to put .zip on the end for GitHub to allow the upload, but it is just an xpi file.


[lyz-3.0.1-fx.xpi.zip](https://github.com/willsALMANJ/lyz/files/1546469/lyz-3.0.1-fx.xpi.zip)

**Comment by willsALMANJ** [comment]
Also, please be aware of issue #23. It seems that it is not possible to migrate a LyZ database from Zotero 4 to Zotero 5 right now without some manual modification of the database.

**Comment by Michael-Logies** [comment]
At 11.12.2017 04:45 willsALMANJ wrote:

> You should be able to download the xpi using the "download any way"
> button on this page:
> https://addons.mozilla.org/en-US/firefox/addon/lyz/versions/

This button does not exist in my web browser (Chrome on Win 10).

> I am attaching the latest version from that page.

Thanks!

Michael

**Comment by willsALMANJ** [comment]
Closing this now that the new update channel is set up and the install instructions are updated.
