### ISSUE TITLE
Lyz won't write to bibtex file

### ISSUE THREAD

**Issue by fish-dots** [willsALMANJ/lyz#26]
I've just updated to Zotero 5.0.33 and added Lyz to it on Linux Mint 18.  Updating Zotero and re-adding Lyz after the update to Zotero 5 worked well on both Window 8.1 and 7.  But for Linux, Lyz isn't writing to the bibtex file.  It'll create a new .bib file and gives no error message, but does not add the citation to Lyx or add anything to the .bib file.  The .bib file is completely blank.  It also will not add to previously existing .bib files.

The following was the output for debugging the lyxserver:

`Server.cpp (930): LyXComm: status:31, read_buffer_:, cmd:LYXCMD:lyz:server-get-filename
Server.cpp (1079): Server: Received: 'LYXCMD:lyz:server-get-filename'
Server.cpp (1123): Server: Client: 'lyz' Command: 'server-get-filename' Argument: ''
Server.cpp (967): LyXComm: Sending 'INFO:lyz:server-get-filename:/home/user/newfile1.lyx
'
Server.cpp (782): LyXComm: Closing connection
Server.cpp (742): LyXComm: Opening connection
Server.cpp (775): LyXComm: Connection established
`

The lyz.sqlite file has the paths for the Lyx files and the associated .bib files, but the keys section has no entries.

**Comment by willsALMANJ** [comment]
Odd, the bib file gets written for me on Linux.... The bib file is created by LyZ using the Zotero translator selected in LyZ's settings, so LyX and the lyxpipe are not involved in that part of the process. Which version of LyZ are you using? I'd guess maybe the translator was generating empty output, but you should still get the first line with item hashes in the bib file. I will try to think of other things to try. You could try installing LyZ into a clean Zotero profile (I think `zotero --ProfileManager` should let you do this).

**Comment by fish-dots** [comment]
This is the file name for the LyZ file (from the Firefox download page): lyz-3.0.2-fx.xpi

Creating a new Zotero profile didn't change anything.  Still a completely blank bib file.

**Comment by willsALMANJ** [comment]
Okay, thanks for testing. When you say that it gives no error message, do you mean that no error pops up or nothing appears in the error console? You can open the error console by using `zotero --jsconsole` to open Zotero.

**Comment by fish-dots** [comment]
I seem to have found the problem after using the error console.  Apparently the permissions on the files in the .mozilla folder were set such that zotero was denied permission to them.  Changing the permissions fixed the problem.

**Comment by willsALMANJ** [comment]
Great, I'm glad that it is fixed.
