### ISSUE TITLE
how to set "extensions.lyz.use_utf8' to 'true' on LyZ 4.00

### ISSUE THREAD

**Issue by MatixR** [willsALMANJ/lyz#27]
Hi, 

There are some chinese characters in my literature, and they are displayed as ? . 
I realizes that  "extensions.lyz.use_utf8" need to be set "Ture", But I can not find the option. Can you show me where it is? 

Thanks

**Comment by willsALMANJ** [comment]
You can get to the config editor (equivalent of `about:config` in Firefox) by this sequence:

1. Open Zotero preferences (in Edit menu on Linux and Windows and Options on macOS, I think).
2. Select the Advanced tab.
3. Click on the "Config editor" button near the bottom.
