### ISSUE TITLE
Can't create or select a bib file

### ISSUE THREAD

**Issue by tluchko** [willsALMANJ/lyz#31]
I just installed the latest version of LyX (2.3.3), Zotero (5.0.75) and LyZ (4.1.0) on to a mac (10.13.6) and am having trouble getting LyZ to create a new bib file.  

I have the pipe properly setup.  When I try to cite a paper for the first time, I get the usual dialog
<img width="440" alt="image" src="https://user-images.githubusercontent.com/31545346/66440580-58064080-e9e8-11e9-99c4-61f98630a191.png">
Whether I hit OK or Cancel the dialog disappears and nothing happens.  There is no file dialog and nothing happens in LyX. 

We have tried installing and reinstalling, and rebooting the machine.  Nothing helps.  We tried looking at the Zotero error console, but no messages appear. I have LyZ running on several Macs, most with OS 10.13.6, without any problems.

Any suggestions?

**Comment by willsALMANJ** [comment]
Hmmm, I will test myself soon and see if I can reproduce the problem. Is there a difference between the configuration you give that does not work now and the ones that have been working for you? Is it upgrading Zotero to 5.0.75 that leads to the problem? Zotero 5.0.75 updated the underlying runtime. I tried to account for this in LyZ 4.1.0, but maybe I missed something.

**Comment by tluchko** [comment]
It does seem to have something to do with Zotero 5.0.75.  I just updated an installation on another computer from 5.0.74 (which worked fine) to 5.0.75 and I now get the same symptoms as described for the fresh install.  

Fortunately, creating new citations in LyX files that are already associated with LyZ still works.

**Comment by willsALMANJ** [comment]
Okay, I reproduced the behavior you see with Zotero 5.0.75. I also double checked that the beta I had tested on before (Zotero-5.0.75-dev.1+2a613258e) did not have this problem. I will try to figure out what changed between that version and the final release.

**Comment by willsALMANJ** [comment]
Okay, I pushed a new release which I think should fix the problem. It was previously announced that 5.0.75 would introduce changes to the backend. I added a conditional to behave differently for versions less than 5.0.75 vs. versions greater, but it seems that an extra release with the old backend was made as 5.0.75 and the backend changes will not be until 5.0.76 or later. I changed LyZ to check the backend version instead of the Zotero version.

Please re-open if the new version doesn't fix the problem (it did for me).

**Comment by tluchko** [comment]
Yes.  This fixed the problem for me as well.

Thank you for maintaining LyZ and the quick fix!
