### ISSUE TITLE
Zotero 6.0 and LyZ

### ISSUE THREAD

**Issue by adessec** [willsALMANJ/lyz#41]
After upgrading to Zotero 6.0 LyZ does not seem to work any more. Are there any suggestions how to proceed?

**Comment by wshanks** [comment]
There is a bad regex that checks for the version number of Zotero. It expects N.N.N and the current version is 6.0. I will try to fix it soon when I have time. Maybe Zotero 6.0.1 will come out and resolve the issue any way :slightly_smiling_face:

**Comment by adessec** [comment]
With the availability of Zotero 6.0.1 everything should work again as expected. A bit of patience is of course a good idea. Thank you for making LyZ!
