### ISSUE TITLE
can't be installed on Firefox-98

### ISSUE THREAD

**Issue by gour** [willsALMANJ/lyz#42]
Hello, I'm using Debian (Sid) and have Firefox-98, but when I try to install this extension Firefox does complain with:

```
about:addons
This addon could not be installed because it appears to be corrupt.
```

Any hint?

**Comment by gour** [comment]
Ahh, I mixed things - too many do to - it is supposed to be install in Zotero: :blush:

**Comment by wshanks** [comment]
Yes, that's right. If you come across documentation somewhere describing it as a Firefox extension, we can try to get it updated.
