### ISSUE TITLE
Bib-file not being updated

### ISSUE THREAD

**Issue by dpprdan** [willsALMANJ/lyz#6]
I've got pretty much the same problem as ser [https://github.com/willsALMANJ/lyz/issues/4]. So multi-document file in LyX, one .bib file. When I click "Update BibTeX", LyZ shows the "You are going to update BibTeX database:" warning with the correct path/file. But when I hit okay, the .bib file is not being updated. 
LyX shows the following debug messages:

15:17:08.615: D:/correct/path/to/file.lyxServer.cpp (633): LyXComm: nbytes:31, iobuf:, cmd:LYXCMD:lyz:server-get-filename
Server.cpp (1078): Server: Received: 'LYXCMD:lyz:server-get-filename'
Server.cpp (1122): Server: Client: 'lyz' Command: 'server-get-filename' Argument: ''
Server.cpp (651): LyXComm: Sending 'INFO:lyz:server-get-filename:D:/correct/path/to/file.lyx
'
Server.cpp (633): LyXComm: nbytes:31, iobuf:, cmd:LYXCMD:lyz:server-get-filename
Server.cpp (1078): Server: Received: 'LYXCMD:lyz:server-get-filename'
Server.cpp (1122): Server: Client: 'lyz' Command: 'server-get-filename' Argument: ''
Server.cpp (651): LyXComm: Sending 'INFO:lyz:server-get-filename:D:/correct/path/to/file.lyx
'

I also tried renaming the BibTeX record to no avail. Adding new references via "cite in LyX" still works. The BibTeX update worked fine with the same files just a few days ago. What may have broken it is that I tried to change the export format from BibTeX to BibLaTeX in the LyZ settings. I changed it back, but also no success.

Any ideas?

Zotero 4.0.19, LyZ 2.1.7

**Comment by Tobelix** [comment]
Hi, got the same problem (can not update the .bib file) i looked at the firefox browser console and get the error:
Parameter 0 is undefined in Zotero.DB.getStatement() [QUERY: SELECT ROWID FROM items WHERE libraryID IS NULL AND key=?] db.js:324:0
uncaught exception: Parameter 0 is undefined in Zotero.DB.getStatement() [QUERY: SELECT ROWID FROM items WHERE libraryID IS NULL AND key=?]

Further i checked my sqlite file but i cannot find any unwritten cells. Is there another possibility which causes this problem?
